spring.application.name=producer

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.value.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value.value-serializer=org.apache.kafka.common.serialization.StringSerializer

kafka.topic.name=commkafka

server.port=8081